swagger: '2.0'
info:
  title: Tie-In API
  description: Scrum development application
  version: 1.0.0
host: tieinservice.herokuapp.com
schemes:
  - https
basePath: /api
produces:
  - application/json
paths:
  /users:
    get:
      summary: Get users
      tags:
        - User
      parameters:
        - name: organization
          in: query
          description: organization id
          required: true
          type: number
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                username:
                  type: string
                email:
                  type: string
        '422':
          description: Unprocessable entity
          schema:
            type: object
            properties:
              errors:
                type: object
                description: "Error paramters as key"
    post:
      summary: Create new user (Regist)
      parameters:
        - name: user
          in: body
          description: user parameters
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                description: Username
              email:
                type: string
                description: Password
              password:
                type: string
                description: Password
              password_confirmation:
                type: string
                description: Password confirmation
              first_name:
                type: string
                description: Firstname
              last_name:
                type: string
                description: Lastname
              phone_number:
                type: string
                description: Password
              birth_date:
                type: string
                description: DD/MM/YYYY
      tags:
        - User
      responses:
        '200':
          description: Success
          schema:
            type: object
            description: "User properties with auth_token"

        '422':
          description: Unprocessable entity
          schema:
            type: object
            properties:
              errors:
                type: object
                description: "Error paramters as key"
  /sessions:
    post:
      summary: Sessions
      description: Login
      parameters:
        - name: session
          in: body
          description: User information
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                description: Username or email
              password:
                type: string
                description: Password
      tags:
        - Session
      responses:
        '200':
          description: An array of price estimates by product
          schema:
            type: object
            properties:
              id:
                type: integer
              email:
                type: string
              username:
                type: string
              auth_token:
                type: string
              firstname:
                type: string
              lastname:
                type: string
              birth_date:
                type: string
              phone_number:
                type: string
        '422':
          description: Unprocessable entity
          schema:
            type: object
            properties:
              errors:
                type: object
                description: "Invalid email/username or password"
  /organizations:
    post:
      summary: Organization
      description: Create organization
      parameters:
        - name: Authorization
          in: header
          description: user's auth_token
          required: true
          type: string
        - name: organization
          in: body
          description: Organization information
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: Organization name
              description:
                type: string
                description: Organization description
              users:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
      tags:
        - Organization
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              organization:
                type: object
                description: organization's properties with proejects
              user:
                type: object
                description: current user properties with organizations
        '422':
          description: Unprocessable entity
          schema:
            type: object
            properties:
              errors:
                type: object
                description: "Error paramters as key"
  /organizations/:organizationId:
    get:
      summary: Orgnization information
      description: See organization information and must have permission
      tags:
        - Organization
      parameters:
        - name: Authorization
          in: header
          description: user's auth_token
          required: true
          type: string
      responses:
        '200':
          description: sucess
          schema:
            type: object
            description: organization's information with projects
            properties:
              id:
                type: integer
              projects:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
        '401':
          description: Permission denied
          schema:
            type: object
            properties:
              errors:
                type: string
                description: permission denied
  /projects:
    post:
      summary: Create new project
      parameters:
        - name: Authorization
          in: header
          description: user's auth_token
          required: true
          type: string
        - name: project
          in: body
          description: Project information
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: Project name
              description:
                type: string
                description: Project description
              users:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
      tags:
        - Project
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              project:
                type: object
                description: project's properties
        '422':
          description: Unprocessable entity
          schema:
            type: object
            properties:
              errors:
                type: object
                description: "Error paramters as key"
  /projects/:projectId:
    get:
      summary: Project information
      description: See project information and must have permission
      tags:
        - Project
      parameters:
        - name: Authorization
          in: header
          description: user's auth_token
          required: true
          type: string
      responses:
        '200':
          description: sucess
          schema:
            type: object
            description: project's information with features and effort estimation
            properties:
              id:
                type: integer
              features:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
              effort_estimations:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
        '401':
          description: Permission denied
          schema:
            type: object
            properties:
              errors:
                type: string
                description: permission denied
  /effort_estimations:
    post:
      summary: Create new effort estimation for planning
      parameters:
        - name: Authorization
          in: header
          description: user's auth_token
          required: true
          type: string
        - name: effort_estimation
          in: body
          description: Effort estimation information
          required: true
          schema:
            type: object
            properties:
              project_id:
                type: integer
                description: Related project id
              t_factor:
                type: integer
                description: Technical factors value
              e_factor:
                type: integer
                description: Technical factors value
              uucp:
                type: integer
                description: UUCP value (from features)
              developers:
                type: integer
                description: Number of developers
        - name: abcd
          in: query
          description: user's auth_token
          required: true
          type: string

      tags:
        - Effort Estimation
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              project_id:
                type: integer
                description: project id
              t_factor:
                type: number
                format: double
                description: techincal factor value
              e_factor:
                type: number
                format: double
                description: environmental factor value
              uucp:
                type: number
                format: double
                description: uucp value
              use_case_point:
                type: number
                format: double
                description: use case points
              lower_weeks:
                type: integer
                description: minimum weeks used
              upper_weeks:
                type: integer
                description: maximum weeks used
        '422':
          description: Unprocessable entity
          schema:
            type: object
            properties:
              errors:
                type: object
                description: "Error paramters as key"
  /effort_estimations/:effort_estimationsId:
    get:
      summary: See effort estimation
      description: See effort estimation  and must have permission
      tags:
        - Effort Estimation
      parameters:
        - name: Authorization
          in: header
          description: user's auth_token
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: object
            description: effort estimations and others planning
            properties:
              effort_estimation:
                type: object
              technical_factor:
                type: object
              environmental_factor:
                type: object
              features:
                type: object
        '401':
          description: Permission denied
          schema:
            type: object
            properties:
              errors:
                type: string
                description: permission denied
